name: Hans Wiederhold
url: 'https://web17.github.io'
description: 'Notes'

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: 'Hans Wiederhold'

sass:
    sass_dir: _sass
    style: :compressed
